### ISSUE TITLE
Store site data separately

### ISSUE THREAD

**Issue by denisdefreyne** [nanoc/features#28]
`nanoc.yaml` is currently used for configuration as well as storing site data. Splitting this up in `nanoc.yaml` (for configuration) and `site.yaml` (for site data) would help:

* Be able to define a scheme for `nanoc.yaml` and validate it
* Create site data without the fear of overwriting built-in config data

Filters and helpers could have their (default) configuration in a sub-hash, e.g.

```yaml
helpers:
  render:
    super_fast_rendering: true

checks:
  internal_links:
    exclude:
      - whatever
```
