### ISSUE TITLE
Pure-YAML Rules file

### ISSUE THREAD

**Issue by denisdefreyne** [nanoc/features#29]
It might be worth allowing the Rules file to be not pure Ruby, but rather a less powerful (configuration) language.

Advantages:

* Fast to parse
* Side-effect free
* Can be checked statically ahead of time
* Does not require learning Ruby

```yaml
items:
  - match: "/**/*.md"
    actions:
      - filter: kramdown
      - write: "${item.identifier.without_ext}.html"
  - match: "/**/*.md"
    rep: raw
    actions:
      - write: "${item.identifier.without_ext}.txt"
  - match: "/**/*"
    actions:
      - write: "${item.identifier.without_ext}"

layouts:
  - match: "/**/*"
    filter: erb
```
