### ISSUE TITLE
Schema-checked configuration file

### ISSUE THREAD

**Issue by denisdefreyne** [nanoc/features#32]
(Depends on #28)

Typos in the configuration file will go unnoticed. It would be useful to verify the structure of the configuration file (`nanoc.yaml`) so that unknown attributes are caught at compile time.

**Comment by denisdefreyne** [comment]
More use cases:

```yaml
output_dir: true
# Should error with e.g. “expected output_dir to be a String, not `true`
```

```yaml
environments:
  production:
# Should error with e.g. “expected environments.production to be a Hash not `nil`
```

See https://github.com/nanoc/nanoc/issues/1352.
