### ISSUE TITLE
Simpler hidden-file handling

### ISSUE THREAD

**Issue by denisdefreyne** [nanoc/features#48]
Nanoc currently has two ways of _not_ handling hidden files:

* The data source excludes hidden files, unless they’re explicitly included in `extra_files`.
* Glob patterns don’t match hidden files (because Nanoc does not use `FNM_DOTMATCH`).

It might be possibly to simplify this:

* The data source includes _all_ files (including hidden ones).
* There is a `ignore /**/.*` rule in the Rules file by default.

CC @moll

**Comment by moll** [comment]
I'm all for it! Saves having to list dot-files separately in `data_sources`:

```yaml
data_sources:
  - type: filesystem
    encoding: utf-8
    extra_files:
      - "**/.htaccess"
```
